config/routes.rb
Rails.application.routes.draw do
  root 'reservation_targets#index'

  get 'help' => 'static_pages#help'
  get 'odota' => 'static_pages#about'
  get 'create_admin' => 'admins#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'userlogin'   => 'usersessions#new'
  post 'userlogin'   => 'usersessions#create'
  delete 'userlogout'  => 'usersessions#destroy'
  get 'varaus' => 'reservation_tokens#show'
  get 'uusivaraus' => 'reservation_tokens#new'
  post 'createtoken' => 'reservation_tokens#create'
  post 'removetoken' => 'reservation_tokens#destroy'

  resources :admins
  resources :owners do
    resources :reservation_targets
    resources :users
    resources :feedbacks
  end
  resources :reservation_targets do
    resources :reservation_slots
  end
  resources :reservation_slots
  resources :users do
    resources :reservation_tokens
  end

end

app/models/reservation_target.rb
class ReservationTarget < ActiveRecord::Base
  belongs_to :owner
  belongs_to :reservation_token
  has_many :reservation_slots
  default_scope -> { order(created_at: :desc) }
  validates :owner_id, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :category, presence: true
  validates :timeWindowInDays, presence: true
end

app/controllers/reservation_targets_controller.rb
class ReservationTargetsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show]
  include ReservationTargetsHelper

  def new
    @reservation_target = ReservationTarget.new
  end

  def create
    @reservation_target = current_owner.reservation_targets.build(reservation_target_params)
    if @reservation_target.save
      flash[:success] = "Resurssi Luotu!"
      redirect_to current_owner
    else
      flash[:danger] = "Epäonnistunut Luonti."
      render 'static_pages/home'
    end
  end

  def destroy
  end

  def show
      @target = ReservationTarget.find(params[:id])
      @reservation_slots = ReservationSlot.where(reservation_target_id: @target.id)
      @cleared = clear_old_one_time_tokens(@reservation_slots)
      @userHasTokensToUse = check_if_current_user_has_tokens(@target.id)
  end

  def index
    if userlogged_in?
      @targetList = ReservationTarget.where(owner_id: current_user.owner_id)
    else
      redirect_to userlogin_path
    end
  end

  private

  def reservation_target_params
    params.require(:reservation_target).permit(:name, :category)
  end
end

app/helpers/reservation_targets_helper.rb
module ReservationTargetsHelper

  include ReservationSlotsHelper



  def current_owner
    @owner = Owner.find_by_id(params[:format])
  end

  def get_adjusted_day_index(iToday, iDayIndex)

    @returnValue = iToday + iDayIndex - 1
    if @returnValue > 7
      @returnValue -= 7
    end
    return @returnValue
  end

  def check_if_current_user_has_tokens(targetId)
    current_user
    @userTokens = ReservationToken.where("user_id = ? and reservation_target_id = ?", @current_user.id, targetId).order(:tokenType)
    @userTokens.each do |t|
      if(ReservationSlot.find_by(reservation_token_id: t.id) == nil)
        return true
      end
    end
    return false
  end

  def clear_old_one_time_tokens(iSlots)
    @numberCleared = 0

    iSlots.each do |s|
      if(s.reservation_token_id != nil)
        @token = ReservationToken.find_by_id(s.reservation_token_id)
        if(@token.tokenType == token_type_use_once())
          if(@token.useDay < DateTime.now.utc)
            s.reservation_token_id = nil
            s.save
            @numberCleared = @numberCleared + 1
          end
        end
      end
    end
    return @numberCleared
  end

  def selected_target
  end
end

app/views/reservation_targets/_getnew.html.erb
<div class="getnew-container">
  <h3 class="getnew">Lisää tai poista varauksia <%= link_to "täältä.", uusivaraus_path(user_id: current_user.id, reservation_target_id: @target.id) , class: "text-link"%></h3>
</div>

app/views/reservation_targets/_reservation_target.html.erb
<li>
    <% if(reservation_target.name != "Kuivaushuone") %>
    <%= link_to reservation_target.name, reservation_target, class: "link-button button-large blue" %>
    <% else %>
    <p>Pilotti on ohi. Kiitos kaikille käytöstä.</p>
    <p>Uusi varausjärjestelmä korvaa tämän ja on käytössä osoitteessa <a href="https://hakolahdentie2.com">hakolahdentie2.com</a>.</p>
    <p>Käy rekisteröitymässä ja pääset varaamaan saunavuoroja pikapuoliin.</p>
    <% end %>
</li>

app/views/reservation_targets/index.html.erb
<div class="page-header-wide">
  <h1 class="">Varaukset</h1>
</div>
<ul class="reservation-target-list">
  <%=render @targetList %>
</ul>
<h3 class="middle">
  Muuta salasana <%= link_to "täältä.", edit_user_path(current_user), class: "text-link" %>
</h3>
<h3 class="middle">
  Lähetä palautetta <%= link_to "täältä.", new_owner_feedback_path(Owner.find_by_id(current_user.owner_id)), class: "text-link"%>
</h3>

app/views/reservation_targets/new.html.erb
<h1>Luo uusi Resurssi</h1>
<%= form_for(@reservation_target) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <br>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :category %>
  <br>
  <%= f.number_field :category %>
  <br>
  <%= f.submit "Luo Resurssi" %>
<% end %>

app/views/reservation_targets/show.html.erb
<%
  @dayNames = ["Maanantai", "Tiistai", "Keskiviikko", "Torstai", "Perjantai", "Lauantai", "Sunnuntai"]
  @todayDayNum = DateTime.now.strftime("%u").to_i
%>

<div class="reservation-target-container">
  <div class="help-container">
    <%= link_to "Käyttöohje", help_path, class: "corner-button text-link" %>
  </div>


  <div class="page-header-wide">
    <h1 class=""><%= @target.name %></h1>
  </div>

  <div class="own-schema-container">
    <div class="date-container">
      <p class="date"> Varauksesi </p>
    </div>
    <div class="slots-container">
      <% if (@userTokens.count != 0) %>
        <%= render @userTokens%>
      <% else %>
        <h2 class="getnew warning">Et voi varata vuoroja.</h2>
      <% end %>
    </div>
      <%# uncomment the following line to enable modifying tokens %>
      <%#= render 'reservation_targets/getnew' %>
  </div>

<% for @dayIndex in 1..@target.timeWindowInDays
      @di = get_adjusted_day_index(@todayDayNum, @dayIndex)
      @slotsForTheDay = @reservation_slots.where("day = ?", @di).order(:startTime)
      if(@slotsForTheDay.count > 0) %>

        <div class="schema-day-container">
          <div class="date-container">
            <p class="date"><%= @dayNames[@di-1] %></p>
          </div>
          <div class="slots-container">
            <%= render @slotsForTheDay %>
          </div>
        </div>
      <% end
   end %>


</div>

<script>
$(document).ready(function(){
  $('.slot').click(function(){
    var slotid = this.id;

    if ($('#'+slotid+' > .res-info-container > .no-confirm').is(":visible")) {

      // close others
      $('.confirm').hide(0);
      $('.no-confirm').show(0);

      //open slot
      $('#'+slotid+' > .res-info-container > .no-confirm').hide(0);
      $('#'+slotid+' > .res-info-container > .confirm').slideDown(50);
    } else if (slotid == "others-slot") {
      $('.confirm').hide(0);
      $('.no-confirm').show(0);
    }
  });
});
</script>