config/routes.rb
Rails.application.routes.draw do
  root 'reservation_targets#index'

  get 'help' => 'static_pages#help'
  get 'odota' => 'static_pages#about'
  get 'create_admin' => 'admins#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'userlogin'   => 'usersessions#new'
  post 'userlogin'   => 'usersessions#create'
  delete 'userlogout'  => 'usersessions#destroy'
  get 'varaus' => 'reservation_tokens#show'
  get 'uusivaraus' => 'reservation_tokens#new'
  post 'createtoken' => 'reservation_tokens#create'
  post 'removetoken' => 'reservation_tokens#destroy'

  resources :admins
  resources :owners do
    resources :reservation_targets
    resources :users
    resources :feedbacks
  end
  resources :reservation_targets do
    resources :reservation_slots
  end
  resources :reservation_slots
  resources :users do
    resources :reservation_tokens
  end

end

app/models/reservation_token.rb
class ReservationToken < ActiveRecord::Base
  belongs_to :user
  belongs_to :reservation_slot
  has_one :reservation_target
  validates :reservation_target_id, presence: true
  validates :user_id, presence: true
end

app/controllers/reservation_tokens_controller.rb
class ReservationTokensController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show]

  include ReservationSlotsHelper
  include ReservationTokensHelper

  def new
    if params[:reservation_target_id] == nil
      redirect_to root_url
    else
      #@token = ReservationToken.new
      @target = ReservationTarget.find(params[:reservation_target_id])
    end
    @tokensToRemove = ReservationToken.where("user_id = ? and reservation_target_id = ?", current_user.id, params[:reservation_target_id]).order(:tokenType)
  end

  def create
    @token = ReservationToken.create() do |t|
      t.user_id = current_user.id
      t.reservation_target_id = params[:reservation_target_id]
      t.tokenType = params[:tokenType]
    end
    if @token.save
      write_token_log_entry("LISÄÄVARAUS: ", @token)
      flash[:success] = "Varaus luotu."
      redirect_to "/reservation_targets/" + params[:reservation_target_id].to_s
    else
      flash[:danger] = "Jokin meni pieleen."
      render 'new'
    end
  end

  def destroy
    @token = ReservationToken.find_by_id(params[:id])
    write_token_log_entry("POISTAVARAUS: ", @token)
    if @token.destroy
      flash[:success] = "Varaus poistettu."
      redirect_to "/reservation_targets/" + params[:reservation_target_id].to_s
    else
      flash[:danger] = "Jokin meni pieleen."
      render 'new'
    end
  end

  def show
    current_user

    if(@current_user != nil)
      @userId = @current_user.id ## replace this with selecting the current user ID...
      @reservation_tokens = ReservationToken.where(user_id: @userId).select(:reservation_target_id).distinct
      if(@reservation_tokens.length == 1)
        @urltogo = "/reservation_targets/" + @reservation_tokens[0].reservation_target_id.to_s
        redirect_to @urltogo
      end
    else
      @userId = 0
    end
  end

end

app/helpers/reservation_tokens_helper.rb
module ReservationTokensHelper


  def write_token_log_entry(oper, tkn)
    $target = ReservationTarget.find_by_id(tkn.reservation_target_id)
    @theevent = oper + "Tapahtumaaika: "+ DateTime.now.to_s + ", Type: " + token_type_to_s(tkn.tokenType) + ", Käyttäjä: " + current_user.name + ", Kohde: " + $target.name  + ", Käyttöpäivä: " + tkn.useDay.to_s
    Reservationlog.create!(owner_id: @current_user.owner_id, logstr: @theevent).save

  end

end

app/views/reservation_tokens/_reservation_token.html.erb
<%
  @dayNames = ["Maanantai", "Tiistai", "Keskiviikko", "Torstai", "Perjantai", "Lauantai", "Sunnuntai"]
  @slot = ReservationSlot.find_by(reservation_token_id: reservation_token.id)
  @dayString = ""
  @timeString = ""
  @stateString = ""
  @typeString = ""


  if(@slot != nil)
    if(@slot.startTime < 1000)
      @timeString =  @slot.startTime.to_s.slice(0) + ":" + @slot.startTime.to_s.slice(1..2)
    else
      @timeString =  @slot.startTime.to_s.slice(0..1) + ":" + @slot.startTime.to_s.slice(2..3)
    end

    if(@slot.endTime < 1000)
      @timeString += "-" + @slot.endTime.to_s.slice(0) + ":" + @slot.endTime.to_s.slice(1..2)
    else
      @timeString += "-" + @slot.endTime.to_s.slice(0..1) + ":" + @slot.endTime.to_s.slice(2..3)
    end

    @stateString = "Käytössä"
    @dayString = @dayNames[@slot.day-1]
  else
    @timeString = ""
    @stateString = "Ei käytössä"
    @dayString = ""
  end

  if(reservation_token.tokenType == token_type_permanent())
    @typeString = "Vakiovaraus"
  else
    @typeString = "Kertavaraus"
  end

%>
<div class="small-slot slot">
<% if(reservation_token.tokenType == token_type_permanent()) %>
  <div class="small-indicator weekly-ind"></div>
<%else%>
  <div class="small-indicator onetime-ind"></div>
<%end%>
  <div class="small-res-info-container">
    <p class="res-username"> <%=@typeString + ": " + @stateString %></p>
    <p class="res-time"><%= @dayString + " " + @timeString%></p>
  </div>
</div>

app/views/reservation_tokens/new.html.erb
<h1>Uusi varaus</h1>
<h2 class="middle">Kohde: <%= @target.name %></h2>
<%= link_to "Takaisin", "/reservation_targets/" + @target.id.to_s, class: "link-button button-large blue" %>
<% if(@target.category == 1)%>
  <div id="vakio-res" class="button-confirmable button-large green">
    <p class="confirmable-text">Luo Vakiovaraus</p>
    <%= link_to "Luo", createtoken_path(reservation_target_id: @target.id, tokenType: 1), method: "post", class: "confirm-button" %>
  </div>

<%end%>

  <div id="kerta-res" class="button-confirmable button-large green">
    <p class="confirmable-text">Luo Kertavaraus</p>
    <%= link_to "Luo", createtoken_path(reservation_target_id: @target.id, tokenType: 2), method: "post", class: "confirm-button" %>
  </div>


<%
@tokensToRemove.each do |t|

  @buttonid = "buttonid-" << t.id.to_s

  @tokenText1 = ""
  @tokenText2 = ""
  if (t.tokenType == 1)
    @tokenText1 = "Vakiovaraus"
    @tokenText2 = "Vakiovarauksen"
  end
  if (t.tokenType == 2)
    @tokenText1 = "Kertavaraus"
    @tokenText2 = "Kertavarauksen"
  end

  if(ReservationSlot.find_by(reservation_token_id: t.id) == nil)
%>

  <div id="<%= @buttonid %>" class="button-confirmable button-large red">
    <p class="confirmable-text">Poista <%= @tokenText1 %></p>
    <%= link_to  "Poista", removetoken_path(id: t.id, reservation_target_id: @target.id), method: "post", class: "confirm-button" %>
  </div>
  <%end%>
<%end%>

<p class="note">HUOM! Voit ainoastaan poistaa ei-käytössä olevia varauksia.</p>

<script>
$(document).ready(function(){
  $('.button-confirmable').click(function(){
    var buttonid = this.id;

    if (!$('#'+buttonid+' > .confirm-button').is(":visible")) {

      // close others
      $('.confirm-button').hide(0);

      //open slot
      $('#'+buttonid+' > .confirm-button').slideDown(50);
    }
  });
});
</script>

app/views/reservation_tokens/show.html.erb
<div class="reservation-token-list-container">
  <% if @reservation_tokens != nil %>
    <div class="page-header-narrow">
      <h1>Varaukset</h1>
    </div>
    <% if @reservation_tokens.count > 0 %>
      <ul class="reservation-token-list">
        <%= render @reservation_tokens %>
      </ul>
      <% else %>
        Sinulla ei ole oikeutta varauksiin. Ole yhteydessä isännöitsijään.
    <% end %>
  <%else%>
      Sinun täytyy ensin kirjautua sisään, jotta voit käyttää tätä sovellusta.
  <% end %>
</div>